<div id="bread-crumbs-wrap">
    <ul>
        <li><a href="">home</a></li>
        <li>Whoops, Not found</li>
    </ul>
</div>

<div id="content-610" class="alignleft">
    <h1>Item(s) not found (yet)</h1>

    <div class="fancy-header">
        <h5>Whoops, the item you are looking for could not be found (yet)</h5>
    </div>
    <p>
        Do to reorganization of the site, some components are not available (yet) at the moment, please check back in a couple of days.
    </p>
    <p>
        So where did all the content go. Because made the choice of switching to a new ORM (Object Relation Model, on our case Doctrine) the content could not easily converted in this new system.
    </p>
    <p>
        We are working our best to get it back online within our new system as soon as possible.
    </p>
</div>

<div id="sidebar-wrap" class="right-bar">
    <div id="border-topend"></div>

    <div id="sidebar-content">

      <section class="sidebar-widget">

          <? // $this->partial('sidebar-widgets/news', array('news' => $this->news)); ?>

          <?= $this->partial('sidebar-widgets/social-networks'); ?>

          <?= $this->partial('sidebar-widgets/twitter'); ?>

          <?= $this->partial('sidebar-widgets/adds'); ?>

        </section>
    </div>

    <div id="border-bottomend"></div>
</div>