 <div class="sitebar-widget">
    <div class="sidebar-header">
        <h4>Advertisements</h4>
    </div>
  <script type="text/javascript"><!--
        google_ad_client = "ca-pub-0000000000000";
        /* halve banner */
        google_ad_slot = "0000000000";
        google_ad_width = 234;
        google_ad_height = 60;
        //-->
    </script>
    <script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
    <br />
    <br />
    <script type="text/javascript"><!--
        google_ad_client = "ca-pub-0000000000000000";
        /* skyscraper 160 */
        google_ad_slot = "000000000";
        google_ad_width = 160;
        google_ad_height = 600;
        //-->
    </script>
    <script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
</div>