<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>website name</title>
</head>
<body>
    
    <header>
        here your header
    </header>
       
    
    <div id="content">
        <?= $this->content; ?>
    </div>


    <footer>
        here your footer
    </footer>

    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <script src="/scripts/jquery.prettyPhoto.js" type="text/javascript"></script>
</body>
</html>